language: node_js
node_js:
  - '8.10'
sudo: false
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run sw-precache
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master