language: node_js
node_js:
  - '8.10'
sudo: false
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run sw-precache
  - yarn run build
  - git status
deploy:
  provider: pages
  local_dir: ./docs
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master