language: node_js
node_js:
  - '8.10'
sudo: false
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run sw-precache
  - yarn run build
  - git add .
  - git commit -m 'new build'
  - git push origin HEAD:master
branches:
  only:
  - master