language: node_js
node_js:
  - '8.10'
sudo: false
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run sw-precache
  - yarn run build
  - travis setup releases --pro
  - git add .
  - git commit -m 'new build'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master